import type { ComponentProps } from 'react';
import type MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';

type Glyph = ComponentProps<typeof MaterialCommunityIcons>['name'];

/**
 * KeePass's 69 standard icons, by index (the number stored in the .kdbx), as
 * the nearest Material Design glyph. KeePassXC shows its own artwork for the
 * same index, so a choice made here means the same thing there.
 */
export const STANDARD_ICONS: { glyph: Glyph; label: string }[] = [
  { glyph: 'key', label: 'Key' },
  { glyph: 'earth', label: 'World' },
  { glyph: 'alert', label: 'Warning' },
  { glyph: 'server', label: 'Server' },
  { glyph: 'folder-star', label: 'Marked folder' },
  { glyph: 'forum', label: 'Chat' },
  { glyph: 'puzzle', label: 'Parts' },
  { glyph: 'notebook', label: 'Notepad' },
  { glyph: 'web', label: 'Web' },
  { glyph: 'card-account-details', label: 'Identity' },
  { glyph: 'file-document', label: 'Document' },
  { glyph: 'camera', label: 'Camera' },
  { glyph: 'remote', label: 'Remote' },
  { glyph: 'key-chain', label: 'Keys' },
  { glyph: 'flash', label: 'Energy' },
  { glyph: 'scanner', label: 'Scanner' },
  { glyph: 'star-circle', label: 'Favourite site' },
  { glyph: 'disc', label: 'Disc' },
  { glyph: 'monitor', label: 'Monitor' },
  { glyph: 'email', label: 'Email' },
  { glyph: 'cog', label: 'Configuration' },
  { glyph: 'clipboard-check', label: 'Clipboard' },
  { glyph: 'file-plus', label: 'New document' },
  { glyph: 'television', label: 'Screen' },
  { glyph: 'flash-alert', label: 'High voltage' },
  { glyph: 'mailbox', label: 'Mailbox' },
  { glyph: 'content-save', label: 'Disk' },
  { glyph: 'harddisk', label: 'Drive' },
  { glyph: 'file-question', label: 'Unknown document' },
  { glyph: 'console-line', label: 'Secure terminal' },
  { glyph: 'console', label: 'Terminal' },
  { glyph: 'printer', label: 'Printer' },
  { glyph: 'apps', label: 'Programs' },
  { glyph: 'play-circle', label: 'Run' },
  { glyph: 'tune', label: 'Settings' },
  { glyph: 'laptop', label: 'Computer' },
  { glyph: 'archive', label: 'Archive' },
  { glyph: 'bank', label: 'Banking' },
  { glyph: 'microsoft-windows', label: 'Windows' },
  { glyph: 'clock-outline', label: 'Clock' },
  { glyph: 'email-search', label: 'Email search' },
  { glyph: 'flag', label: 'Flag' },
  { glyph: 'memory', label: 'Memory' },
  { glyph: 'delete', label: 'Trash' },
  { glyph: 'note-text', label: 'Note' },
  { glyph: 'close-circle', label: 'Expired' },
  { glyph: 'information', label: 'Info' },
  { glyph: 'package-variant', label: 'Package' },
  { glyph: 'folder', label: 'Folder' },
  { glyph: 'folder-open', label: 'Open folder' },
  { glyph: 'folder-zip', label: 'Packed folder' },
  { glyph: 'lock-open', label: 'Unlocked' },
  { glyph: 'file-lock', label: 'Locked document' },
  { glyph: 'check-circle', label: 'Checked' },
  { glyph: 'pencil', label: 'Pen' },
  { glyph: 'image', label: 'Picture' },
  { glyph: 'book', label: 'Book' },
  { glyph: 'format-list-bulleted', label: 'List' },
  { glyph: 'account-key', label: 'User key' },
  { glyph: 'hammer-wrench', label: 'Tools' },
  { glyph: 'home', label: 'Home' },
  { glyph: 'star', label: 'Star' },
  { glyph: 'penguin', label: 'Linux' },
  { glyph: 'feather', label: 'Feather' },
  { glyph: 'apple', label: 'Apple' },
  { glyph: 'wikipedia', label: 'Wiki' },
  { glyph: 'currency-usd', label: 'Money' },
  { glyph: 'certificate', label: 'Certificate' },
  { glyph: 'cellphone', label: 'Phone' },
];
